### PR TITLE
number game.cpp

### PR DESCRIPTION
**Pull request by Kritikmahajan**

### CODE REVIEW

**Comment by Kritikmahajan** [comment]
@bishweashwarsukla  plz make this repository accepted by hactoberfest. As this is not accepted by hacktoberfest.
Also add readme.md

**Comment by bishweashwarsukla** [comment]
Check on website of hacktoberfest 2022. Your PR must be their in 7 day review period. It will get accepted after 7 day review period

**Comment by Kritikmahajan** [comment]
In hacktoberfest website not showing in waiting period rather its is in excluded tag

**Comment by bishweashwarsukla** [comment]
Check again after sometime. I have changed the label

**Pull request merged**
